### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by JeremyScherer-NRCS** [USDA-NRCS/Extract-CLU-Tool#1]
A user attempting to run the tool using ArcMap 10.6 received this error:

There are approximately 35 CLUs within AOI

	  File "C:\HEL\Extract-CLU-Tool-master\Extract-CLU-Tool-master\extract_CLU_by_AOI.py", line 837, in createListOfJSONextents_ArcMap
    if bSpatialRefUpdate:

	UnboundLocalError: local variable 'bSpatialRefUpdate' referenced before assignment

**Comment by ajdiazdk** [comment]
The tool has been updated to fix the bSpatialRefUpdate. This issue only affected execution in ArcMap.

Solution: boolean variable 'bSpatialRefUpdate' is used to determine whether the coordinate system of the user-defined AOI is the same as the ArcMap dataframe.  This variable was relocated outside of nested statement.
