### ISSUE TITLE
Could not determine number of server requests 

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Extract-CLU-Tool#4]
I've downloaded the tool and started from scratch.  I am attempting to export a single county.  I keep getting the error message that the script cannot determine the number of server requests.  
![serv_req_error](https://user-images.githubusercontent.com/63659670/87449135-678f6700-c5c2-11ea-99ae-1426baeda149.JPG)

**Comment by japitts8816** [comment]
I have updated to ArcGIS PRO 2.5.2.

**Comment by dylan-harwell-usda** [comment]
Closing issue - appears to be duplicated by two others that have been addressed/closed.
