### ISSUE TITLE
Error when using in ArcGIS 10.7.1

### ISSUE THREAD

**Issue by japitts8816** [USDA-NRCS/Extract-CLU-Tool#5]
I attempted to use in the ArcGIS 10.7.1 environment.  it is not finding the portal.  
![serv_req_error2](https://user-images.githubusercontent.com/63659670/87453298-e935c380-c5c7-11ea-9573-052705ee9af3.JPG)

**Comment by ajdiazdk** [comment]
GeoPortal must be added to your list of ArcGIS Connections through your ArcGIS Administrator.

![image](https://user-images.githubusercontent.com/15237318/87959530-a7e65d80-ca78-11ea-8f27-a33feebfe44b.png)

**Comment by CEM-NRCS** [comment]
Note: A recent update to Software Center deployed an automatic install that might remove GeoPortal from your list of Portal connections and may have replaced it with the old 10.5 GeoPortal URL.

**Comment by japitts8816** [comment]
I’ll check it this morning.

Julie A. Pitts, GIS Specialist
USDA Natural Resources Conservation Service
Mississippi
601-768-3077

Sapiens qui prospicit
     (Wise is he that looks ahead)

“Ability is what you are capable of doing. Motivation determines what you do.  Attitude determines how well you do it”

**Comment by japitts8816** [comment]
Ok, let me try that.  Thanks!

Julie A. Pitts, GIS Specialist
USDA Natural Resources Conservation Service
Mississippi
601-768-3077

Sapiens qui prospicit
     (Wise is he that looks ahead)

“Ability is what you are capable of doing. Motivation determines what you do.  Attitude determines how well you do it”

**Comment by japitts8816** [comment]
Appears to be wo
![image](https://user-images.githubusercontent.com/63659670/88076877-3a9dff80-cb40-11ea-9630-dd2cde5aba96.png)
rking in ArcGIS Desktop 10.7.1 now that I've made a connection to the GeoPortal.

**Comment by japitts8816** [comment]
Got the tool to work in 10.7.1 after properly connecting to GeoPortal 10.6.1.  However, I'm still unable to get the tool to run in ArcGIS PRO 2.5.  

![image](https://user-images.githubusercontent.com/63659670/88083154-4ee5fa80-cb48-11ea-8d7a-5069cafd72fa.png)

**Comment by dylan-harwell-usda** [comment]
Closing issue - tool is confirmed to work in Pro 2.9 and 3.X
